In [1]:
import os
from datetime import datetime
import shutil
from pathlib import Path
import pandas as pd
import datasets
from datasets import DatasetDict, Dataset
from multitask_trainer import train_eval_model

In [2]:
cache_dir = '../cache'
data_dir = Path('data/hf_berkeley_multi')
output_dir = Path('data/berkeley_dataset_multi_augmented')
TOXIGEN_MAP = {
    'sexuality': ['lgbtq'],
    'disability': ['mental_dis', 'physical_dis']
}

In [3]:
data = datasets.load_dataset("toxigen/toxigen-data", cache_dir=cache_dir)
train_df = data['train'].to_pandas()
shutil.copytree(data_dir, output_dir, dirs_exist_ok=True)
for group_name, tox_targets in TOXIGEN_MAP.items():
    task_dir = f'target={group_name}'
    dataset = DatasetDict.load_from_disk(str(data_dir/task_dir))
    df_aug = train_df[train_df['target_group'].isin(tox_targets)]
    df_aug = pd.DataFrame({'text': df_aug['text'], 'value': 1, 'task_name': group_name})
    df_aug = Dataset.from_pandas(df_aug).cast_column('value', dataset['train'].features['value'])
    dataset['train'] = datasets.concatenate_datasets([dataset['train'], df_aug])
    dataset.save_to_disk(str(output_dir/task_dir))

Casting the dataset:   0%|          | 0/714 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/28409 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5935 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5935 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/1399 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/29094 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5935 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5935 [00:00<?, ? examples/s]

## LoRa

In [4]:
os.environ["CUDA_VISIBLE_DEVICES"]="1"
model_path = "intfloat/e5-large-v2"
model_dir = "outputs/berkeley_toxigen_classifier_multi_e5_large"

In [5]:
print("Training started:", datetime.now())

Training started: 2026-01-18 18:22:38.932753

In [6]:
lora_args = {
    "init_lora_weights": "olora",
    "target_modules": "all-linear"
}
_, results = train_eval_model(model_path, data_dir=output_dir, cache_dir=cache_dir, 
                              save_model_dir=model_dir, output_dir="test-classifier-lora-large", 
                              batch_size=64, num_epochs=20, eval_batch_size=128, 
                              use_lora=True, lora_args=lora_args)
print(results)

Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at intfloat/e5-large-v2 and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight', 'heads.5.1.bias', 'heads.5.1.weight', 'heads.6.1.bias', 'heads.6.1.weight', 'heads.7.1.bias', 'heads.7.1.weight', 'heads.8.1.bias', 'heads.8.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.
2026/01/18 18:22:45 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/01/18 18:22:46 INFO mlflow.store.db.utils: Updating database tables
2026/01/18 18:22:46 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/01/18 18:22:46 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade  -> 451aebb31d03, add metric step
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
2026/01/18 18:22:46 INFO alembic.runtime.migration: Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 1a0cddfcaa16 -> 534353b11cbc, add scorer tables
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 534353b11cbc -> 71994744cf8e, add evaluation datasets
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 71994744cf8e -> 3da73c924c2f, add outputs to dataset record
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade 3da73c924c2f -> bf29a5ff90ea, add jobs table
2026/01/18 18:22:47 INFO alembic.runtime.migration: Running upgrade bf29a5ff90ea -> 1bd49d398cd23, add secrets tables
2026/01/18 18:22:47 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/01/18 18:22:47 INFO alembic.runtime.migration: Will assume non-transactional DDL.
***** Running training *****
  Num examples = 251,368
  Num Epochs = 20
  Instantaneous batch size per device = 64
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 1
  Total optimization steps = 78,560
  Number of trainable parameters = 3,574,825

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-3928
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-42845] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-7856
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-62320] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-11784
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-3928] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-15712
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-7856] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-19640
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-11784] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-23568
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-15712] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-27496
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-23568] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-31424
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-27496] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-35352
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-31424] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 53415
  Batch size = 128
Saving model checkpoint to test-classifier-lora-large/checkpoint-39280
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [test-classifier-lora-large/checkpoint-35352] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from test-classifier-lora-large/checkpoint-19640 (score: 0.93219133202284).

***** Running Prediction *****
  Num examples = 53415
  Batch size = 128

hatespeech
              precision    recall  f1-score   support

           0       0.84      0.94      0.89      4396
           1       0.00      0.00      0.00       290
           2       0.69      0.56      0.61      1249

    accuracy                           0.81      5935
   macro avg       0.51      0.50      0.50      5935
weighted avg       0.77      0.81      0.79      5935

gender
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      4010
           1       0.86      0.86      0.86      1925

    accuracy                           0.91      5935
   macro avg       0.89      0.89      0.89      5935
weighted avg       0.91      0.91      0.91      5935

sexuality
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      4972
           1       0.88      0.77      0.82       963

    accuracy                           0.95      5935
   macro avg       0.92      0.87      0.89      5935
weighted avg       0.94      0.95      0.94      5935

/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

age
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      5834
           1       0.65      0.30      0.41       101

    accuracy                           0.99      5935
   macro avg       0.82      0.65      0.70      5935
weighted avg       0.98      0.99      0.98      5935

religion
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      5082
           1       0.86      0.86      0.86       853

    accuracy                           0.96      5935
   macro avg       0.92      0.92      0.92      5935
weighted avg       0.96      0.96      0.96      5935

contains_hate
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       297
           1       0.95      1.00      0.97      5638

    accuracy                           0.95      5935
   macro avg       0.47      0.50      0.49      5935
weighted avg       0.90      0.95      0.93      5935

origin
              precision    recall  f1-score   support

           0       0.97      0.94      0.95      5023
           1       0.72      0.82      0.77       912

    accuracy                           0.92      5935
   macro avg       0.85      0.88      0.86      5935
weighted avg       0.93      0.92      0.93      5935

race
              precision    recall  f1-score   support

           0       0.91      0.97      0.94      4386
           1       0.90      0.74      0.81      1549

    accuracy                           0.91      5935
   macro avg       0.91      0.85      0.88      5935
weighted avg       0.91      0.91      0.91      5935

disability
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5811
           1       0.67      0.75      0.71       124

    accuracy                           0.99      5935
   macro avg       0.83      0.87      0.85      5935
weighted avg       0.99      0.99      0.99      5935

tokenizer config file saved in outputs/berkeley_toxigen_classifier_multi_e5_large/tokenizer_config.json
Special tokens file saved in outputs/berkeley_toxigen_classifier_multi_e5_large/special_tokens_map.json
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

            task  accuracy  f1_score  precision    recall     kappa   roc_auc
0     hatespeech  0.814490  0.814490   0.814490  0.814490  0.469959       NaN
1         gender  0.907498  0.857440   0.857217  0.857662  0.788977  0.894542
2      sexuality  0.945240  0.820343   0.877069  0.770509  0.788199  0.874796
3            age  0.985341  0.408163   0.652174  0.297030  0.401792  0.647144
4       religion  0.960067  0.860997   0.861502  0.860492  0.837682  0.918637
5  contains_hate  0.949789  0.974248   0.949949  0.999823 -0.000336  0.499911
6         origin  0.924347  0.769389   0.723671  0.821272  0.724356  0.882167
7           race  0.910025  0.810100   0.901821  0.735313  0.751943  0.853521
8     disability  0.987195  0.709924   0.673913  0.750000  0.703396  0.871128

In [7]:
print("Training finished:", datetime.now())

Training finished: 2026-01-19 19:37:59.461138

## Evaluation on HateCheck

In [15]:
from multitask_trainer import evaluate_model
# from multitask_trainer import calculate_scores
evaluate_model(model_dir, 'data/hatecheck_dataset_multi', cache_dir)

loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file config.json from cache at ../cache/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "dtype": "float32",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.5",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file model.safetensors from cache at ../cache/models--intfloat--e5-large-v2/snapshots/f169b11e22de13617baa190a028a32f3493550b6/model.safetensors
Some weights of BertMultiTaskClassifier were not initialized from the model checkpoint at intfloat/e5-large-v2 and are newly initialized: ['heads.0.1.bias', 'heads.0.1.weight', 'heads.1.1.bias', 'heads.1.1.weight', 'heads.2.1.bias', 'heads.2.1.weight', 'heads.3.1.bias', 'heads.3.1.weight', 'heads.4.1.bias', 'heads.4.1.weight', 'heads.5.1.bias', 'heads.5.1.weight', 'heads.6.1.bias', 'heads.6.1.weight', 'heads.7.1.bias', 'heads.7.1.weight', 'heads.8.1.bias', 'heads.8.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
100%|██████████| 7164/7164 [02:30<00:00, 47.63it/s]

Task: gender
Task: sexuality
Task: religion
Task: contains_hate
Task: origin
Task: race
Task: disability

/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

            task  accuracy  f1_score  precision    recall  kappa  roc_auc
0         gender  0.968566  0.968566   0.968566  0.968566    0.0      NaN
1      sexuality  0.769231  0.769231   0.769231  0.769231    0.0      NaN
2       religion  0.900826  0.900826   0.900826  0.900826    0.0      NaN
3  contains_hate  0.687500  0.814815   0.687500  1.000000    0.0      0.5
4         origin  0.896328  0.896328   0.896328  0.896328    0.0      NaN
5           race  0.946058  0.946058   0.946058  0.946058    0.0      NaN
6     disability  0.927686  0.927686   0.927686  0.927686    0.0      NaN